runtime: nodejs
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "{path/to-google-credentials.json}"
  GOOGLE_BUCKET_NAME: "bucket-name"
  ALLOWED_EXTENSIONS: ".csv"
  NODE_ENV: "development"